name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test (Swift ${{ matrix.swift-version }} on ${{ matrix.os }})
    
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: [^6]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Build
      run: swift build -v

